<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Contato
        </div>
    </div>
    
    <?php 
        //objeto form contato
        $form = $this->formContato;
        //preparar elementos do formulario
        $form->prepare();
        //configurar url formulario
        $form->setAttribute('action', $this->url('contatos', array('action'=> 'adicionar')));
    
        // renderiza html <form> com atributos configurados no objeto
        echo $this->form()->openTag($form) 
    ?>
    
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome*:</label>
            <div class="col-lg-9 col-md-9">
                <?php 
                // renderiza html input
                echo $this->formInput($form->get('nome'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('nome'));
                ?>
            </div>
        </div>
 
        <div class="form-group">
            <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Tel. Principal*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($form->get('telefone_principal'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('telefone_principal'));
                ?>
            </div>
        </div>
 
        <div class="form-group">
            <label for="inputTelefoneSecundario" class="col-lg-3 col-md-3 control-label">Tel. Secundário:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($form->get('telefone_secundario'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('telefone_secundario'));
                ?>
            </div>
        </div>
 
        <div class="form-group">
            <label for="inputCaptcha" class="col-lg-3 col-md-3 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
                // renderiza captcha
                echo $this->formCaptcha($form->get('captcha'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('captcha'));
                ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($form->get('id'));
        // renderiza html input hidden csrf
        echo $this->formElement($form->get('security')); 
        ?>
 
        <button type="submit" class="btn btn-primary">Salvar Contato</button>
        <a href="<?php echo $this->url('contatos'); ?>" class="btn btn-default">Voltar</a>
    </div>
 
    <?php // renderiza html </form>
        echo $this->form()->closeTag() 
    ?>
    
</div>